.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 林博仁 <Buo.Ren.Lin@gmail.com>,
.\"
.\" See http://www.debian.org/doc/manuals/maint-guide/dother.en.html#manpage1
.\"
.\" 1. Use this as the template for the manpage for <commandname> after
.\"    renaming this file to <commandname>.1 (if it is for section 1).
.\"
.\" 2. List the path to this file in debian/<packagename>.manpages to
.\"    install this manpage to the target binary package.
.\"
.\" First parameter, HELLO-DEBIAN-PACKAGING, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" 林博仁：Not going to all caps as it looks inconsistent
.TH hello-debian-packaging 1 "19 Jul 2017" "Hello Debian Packaging" "Hello Debian Packaging Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hello-debian-packaging \- A program to print a welcome message to debian packaging

.SH SYNOPSIS
.B hello-debian-packaging

.SH DESCRIPTION
.B hello-debian-packaging
is an example program for debian packaging, it simply print out a welcome message to the standard output device.
\".PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.\" \fBhello-debian-packaging\fP is a program that...

.SH COMMAND\-LINE OPTIONS
This program currently has no commandline options
.\" These programs follow the usual GNU command line syntax, with long
.\" options starting with two dashes (`-').
.\" A summary of options is included below.
.\" For a complete description, see the Info files.
.\" .TP
.\" .B \-h, \-\-help
.\" Show summary of options.
.\" .TP
.\" .B \-v, \-\-version
.\" Show version of program.

.SH SEE ALSO
.BR man-pages (7),
.BR man (7).

.\" .br
.\" The programs are documented fully by
.\" .IR "The Rise and Fall of a Fooish Bar" ,
.\" available via the Info system.